"""add uvt values and exogena generations

The UVT per year plus the record of every attempt to fetch it — the failures
are kept too, because a threshold that quietly used a stale value is exactly
what that table exists to make visible.

Exógena generations keep the XML they produced rather than the rows behind it:
a filed document has to come back byte for byte, and the vouchers underneath it
can move afterwards.

On `accounts`, the DIAN concept an account reports under and whether amounts on
it are the withholding rather than the payment. Both are what let the report be
grouped by third party and concept at all.

Revision ID: 14eff190c2b2
Revises: e0b85c326d15
Create Date: 2026-07-26 08:08:52.615613

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "14eff190c2b2"
down_revision: str | None = "e0b85c326d15"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "uvt_fetch_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SUCCEEDED",
                "FAILED",
                "SKIPPED",
                name="uvt_run_status",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("value", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("detail", sa.String(length=255), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_uvt_fetch_runs_status"), "uvt_fetch_runs", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_uvt_fetch_runs_year"), "uvt_fetch_runs", ["year"], unique=False
    )
    op.create_table(
        "uvt_values",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("value", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "FETCHED", "MANUAL", name="uvt_source", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=50), nullable=True),
        sa.Column("fetched_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("year", name="uq_uvt_values_year"),
    )
    op.create_index(op.f("ix_uvt_values_year"), "uvt_values", ["year"], unique=False)
    op.create_table(
        "exogena_generations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("threshold_uvt", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("uvt_value", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("threshold_pesos", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("filer_nit", sa.String(length=20), nullable=False),
        sa.Column("filer_name", sa.String(length=150), nullable=False),
        sa.Column("record_count", sa.Integer(), nullable=False),
        sa.Column("total_gross", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("total_withheld", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("excluded_count", sa.Integer(), nullable=False),
        sa.Column("xml", sa.Text(), nullable=False),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.Column("generated_by_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["generated_by_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_exogena_generations_generated_at"),
        "exogena_generations",
        ["generated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_exogena_generations_year"),
        "exogena_generations",
        ["year"],
        unique=False,
    )
    op.add_column(
        "accounts", sa.Column("dian_concept", sa.String(length=10), nullable=True)
    )
    # `server_default` so this works on a chart that already has rows; dropped
    # straight after, so the column stays the application's decision.
    op.add_column(
        "accounts",
        sa.Column(
            "is_withholding",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.alter_column("accounts", "is_withholding", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "is_withholding")
    op.drop_column("accounts", "dian_concept")
    op.drop_index(op.f("ix_exogena_generations_year"), table_name="exogena_generations")
    op.drop_index(
        op.f("ix_exogena_generations_generated_at"), table_name="exogena_generations"
    )
    op.drop_table("exogena_generations")
    op.drop_index(op.f("ix_uvt_values_year"), table_name="uvt_values")
    op.drop_table("uvt_values")
    op.drop_index(op.f("ix_uvt_fetch_runs_year"), table_name="uvt_fetch_runs")
    op.drop_index(op.f("ix_uvt_fetch_runs_status"), table_name="uvt_fetch_runs")
    op.drop_table("uvt_fetch_runs")
    # ### end Alembic commands ###
