"""seed countries and colombian departments

Fills the top two levels of the location catalog. Municipalities hang off the
departments created here and are seeded by the next revision.

The rows are written out in full rather than imported from the application
package. A migration has to produce the same result the day it is replayed as it
did the day it ran, and importing a module that later changes would break that.
The cost is that a correction needs a new revision, which is the intent.

Countries are ISO 3166-1 alpha-2. Department codes are the DANE ones, and are
the prefix of every municipality code inside them.

Revision ID: 7355399db43d
Revises: 7c980446df2a
Create Date: 2026-07-26 04:43:58.112935

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7355399db43d"
down_revision: str | None = "7c980446df2a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_COLOMBIA = "CO"

_COUNTRIES: tuple[tuple[str, str], ...] = (
    ("AF", "Afganistán"),
    ("AL", "Albania"),
    ("DE", "Alemania"),
    ("AD", "Andorra"),
    ("AO", "Angola"),
    ("AI", "Anguila"),
    ("AG", "Antigua y Barbuda"),
    ("AQ", "Antártida"),
    ("SA", "Arabia Saudita"),
    ("DZ", "Argelia"),
    ("AR", "Argentina"),
    ("AM", "Armenia"),
    ("AW", "Aruba"),
    ("AU", "Australia"),
    ("AT", "Austria"),
    ("AZ", "Azerbaiyán"),
    ("BD", "Bangladesh"),
    ("BB", "Barbados"),
    ("BH", "Baréin"),
    ("BZ", "Belice"),
    ("BJ", "Benín"),
    ("BM", "Bermudas"),
    ("BY", "Bielorrusia"),
    ("BO", "Bolivia"),
    ("BQ", "Bonaire, Sint Eustatius y Saba"),
    ("BA", "Bosnia y Herzegovina"),
    ("BW", "Botsuana"),
    ("BR", "Brasil"),
    ("BN", "Brunéi"),
    ("BG", "Bulgaria"),
    ("BF", "Burkina Faso"),
    ("BI", "Burundi"),
    ("BT", "Bután"),
    ("BE", "Bélgica"),
    ("CV", "Cabo Verde"),
    ("KH", "Camboya"),
    ("CM", "Camerún"),
    ("CA", "Canadá"),
    ("TD", "Chad"),
    ("CL", "Chile"),
    ("CN", "China"),
    ("CY", "Chipre"),
    ("VA", "Ciudad del Vaticano"),
    ("CO", "Colombia"),
    ("KM", "Comoras"),
    ("CG", "Congo"),
    ("KP", "Corea del Norte"),
    ("KR", "Corea del Sur"),
    ("CR", "Costa Rica"),
    ("CI", "Costa de Marfil"),
    ("HR", "Croacia"),
    ("CU", "Cuba"),
    ("CW", "Curazao"),
    ("DK", "Dinamarca"),
    ("DM", "Dominica"),
    ("EC", "Ecuador"),
    ("EG", "Egipto"),
    ("SV", "El Salvador"),
    ("AE", "Emiratos Árabes Unidos"),
    ("ER", "Eritrea"),
    ("SK", "Eslovaquia"),
    ("SI", "Eslovenia"),
    ("ES", "España"),
    ("US", "Estados Unidos"),
    ("EE", "Estonia"),
    ("ET", "Etiopía"),
    ("PH", "Filipinas"),
    ("FI", "Finlandia"),
    ("FR", "Francia"),
    ("GA", "Gabón"),
    ("GM", "Gambia"),
    ("GE", "Georgia"),
    ("GS", "Georgia del Sur"),
    ("GH", "Ghana"),
    ("GI", "Gibraltar"),
    ("GD", "Granada"),
    ("GR", "Grecia"),
    ("GL", "Groenlandia"),
    ("GP", "Guadalupe"),
    ("GU", "Guam"),
    ("GT", "Guatemala"),
    ("GF", "Guayana Francesa"),
    ("GG", "Guernsey y Alderney"),
    ("GN", "Guinea"),
    ("GQ", "Guinea Ecuatorial"),
    ("GW", "Guinea-Bissau"),
    ("GY", "Guyana"),
    ("HT", "Haití"),
    ("HN", "Honduras"),
    ("HK", "Hong Kong S.A.R."),
    ("HU", "Hungría"),
    ("IN", "India"),
    ("ID", "Indonesia"),
    ("IQ", "Iraq"),
    ("IE", "Irlanda"),
    ("IR", "Irán"),
    ("BV", "Isla Bouvet"),
    ("NF", "Isla Norfolk"),
    ("PN", "Isla Pitcairn"),
    ("IM", "Isla de Man"),
    ("CX", "Isla de Navidad"),
    ("IS", "Islandia"),
    ("KY", "Islas Caimán"),
    ("CC", "Islas Cocos (Keeling)"),
    ("CK", "Islas Cook"),
    ("FO", "Islas Feroe"),
    ("FJ", "Islas Fiyi"),
    ("HM", "Islas Heard y McDonald"),
    ("FK", "Islas Malvinas"),
    ("MP", "Islas Marianas del Norte"),
    ("MH", "Islas Marshall"),
    ("UM", "Islas Menores Alejadas de Estados Unidos"),
    ("SB", "Islas Salomón"),
    ("SJ", "Islas Svalbard y Jan Mayen"),
    ("TC", "Islas Turcas y Caicos"),
    ("VG", "Islas Vírgenes Británicas"),
    ("VI", "Islas Vírgenes de los Estados Unidos"),
    ("AX", "Islas Åland"),
    ("IL", "Israel"),
    ("IT", "Italia"),
    ("JM", "Jamaica"),
    ("JP", "Japón"),
    ("JE", "Jersey"),
    ("JO", "Jordania"),
    ("KZ", "Kazajstán"),
    ("KE", "Kenia"),
    ("KG", "Kirguistán"),
    ("KI", "Kiribati"),
    ("KW", "Kuwait"),
    ("LA", "Laos"),
    ("BS", "Las Bahamas"),
    ("LS", "Lesoto"),
    ("LV", "Letonia"),
    ("LR", "Liberia"),
    ("LY", "Libia"),
    ("LI", "Liechtenstein"),
    ("LT", "Lituania"),
    ("LU", "Luxemburgo"),
    ("LB", "Líbano"),
    ("MO", "Macao R.A.E."),
    ("MK", "Macedonia del Norte"),
    ("MG", "Madagascar"),
    ("MY", "Malasia"),
    ("MW", "Malawi"),
    ("MV", "Maldivas"),
    ("ML", "Mali"),
    ("MT", "Malta"),
    ("MA", "Marruecos"),
    ("MQ", "Martinica"),
    ("MU", "Mauricio"),
    ("MR", "Mauritania"),
    ("YT", "Mayotte"),
    ("FM", "Micronesia"),
    ("MD", "Moldavia"),
    ("MN", "Mongolia"),
    ("ME", "Montenegro"),
    ("MS", "Montserrat"),
    ("MZ", "Mozambique"),
    ("MM", "Myanmar"),
    ("MX", "México"),
    ("MC", "Mónaco"),
    ("NA", "Namibia"),
    ("NR", "Nauru"),
    ("NP", "Nepal"),
    ("NI", "Nicaragua"),
    ("NG", "Nigeria"),
    ("NU", "Niue"),
    ("NO", "Noruega"),
    ("NC", "Nueva Caledonia"),
    ("NZ", "Nueva Zelanda"),
    ("NE", "Níger"),
    ("OM", "Omán"),
    ("PK", "Pakistán"),
    ("PW", "Palaos"),
    ("PS", "Palestina"),
    ("PA", "Panamá"),
    ("PG", "Papúa Nueva Guinea"),
    ("PY", "Paraguay"),
    ("NL", "Países Bajos"),
    ("PE", "Perú"),
    ("PF", "Polinesia Francesa"),
    ("PL", "Polonia"),
    ("PT", "Portugal"),
    ("PR", "Puerto Rico"),
    ("QA", "Qatar"),
    ("GB", "Reino Unido"),
    ("CF", "República Centroafricana"),
    ("CZ", "República Checa"),
    ("CD", "República Democrática del Congo"),
    ("DO", "República Dominicana"),
    ("RE", "Reunión"),
    ("RW", "Ruanda"),
    ("RO", "Rumania"),
    ("RU", "Rusia"),
    ("EH", "Sahara Occidental"),
    ("WS", "Samoa"),
    ("AS", "Samoa Americana"),
    ("BL", "San Bartolomé"),
    ("KN", "San Cristóbal y Nieves"),
    ("SM", "San Marino"),
    ("MF", "San Martín (parte francesa)"),
    ("PM", "San Pedro y Miquelón"),
    ("VC", "San Vicente y las Granadinas"),
    ("SH", "Santa Elena"),
    ("LC", "Santa Lucía"),
    ("ST", "Santo Tomé y Príncipe"),
    ("SN", "Senegal"),
    ("RS", "Serbia"),
    ("SC", "Seychelles"),
    ("SL", "Sierra Leona"),
    ("SG", "Singapur"),
    ("SY", "Siria"),
    ("SO", "Somalia"),
    ("LK", "Sri Lanka"),
    ("ZA", "Sudáfrica"),
    ("SD", "Sudán"),
    ("SS", "Sudán del Sur"),
    ("SE", "Suecia"),
    ("CH", "Suiza"),
    ("SR", "Surinam"),
    ("SZ", "Swazilandia"),
    ("TH", "Tailandia"),
    ("TW", "Taiwán"),
    ("TZ", "Tanzania"),
    ("TJ", "Tayikistán"),
    ("IO", "Territorio Británico del Océano Índico"),
    ("TF", "Territorios Australes Franceses"),
    ("TL", "Timor Oriental"),
    ("TG", "Togo"),
    ("TK", "Tokelau"),
    ("TO", "Tonga"),
    ("TT", "Trinidad y Tabago"),
    ("TM", "Turkmenistán"),
    ("TR", "Turquía"),
    ("TV", "Tuvalu"),
    ("TN", "Túnez"),
    ("UA", "Ucrania"),
    ("UG", "Uganda"),
    ("UY", "Uruguay"),
    ("UZ", "Uzbekistán"),
    ("VU", "Vanuatu"),
    ("VE", "Venezuela"),
    ("VN", "Vietnam"),
    ("WF", "Wallis y Futuna"),
    ("YE", "Yemen"),
    ("DJ", "Yibuti"),
    ("ZM", "Zambia"),
    ("ZW", "Zimbabue"),
)

_DEPARTMENTS: tuple[tuple[str, str], ...] = (
    ("05", "Antioquia"),
    ("08", "Atlántico"),
    ("11", "Bogotá, D.C."),
    ("13", "Bolívar"),
    ("15", "Boyacá"),
    ("17", "Caldas"),
    ("18", "Caquetá"),
    ("19", "Cauca"),
    ("20", "Cesar"),
    ("23", "Córdoba"),
    ("25", "Cundinamarca"),
    ("27", "Chocó"),
    ("41", "Huila"),
    ("44", "La Guajira"),
    ("47", "Magdalena"),
    ("50", "Meta"),
    ("52", "Nariño"),
    ("54", "Norte de Santander"),
    ("63", "Quindío"),
    ("66", "Risaralda"),
    ("68", "Santander"),
    ("70", "Sucre"),
    ("73", "Tolima"),
    ("76", "Valle del Cauca"),
    ("81", "Arauca"),
    ("85", "Casanare"),
    ("86", "Putumayo"),
    ("88", "Archipiélago de San Andrés, Providencia y Santa Catalina"),
    ("91", "Amazonas"),
    ("94", "Guainía"),
    ("95", "Guaviare"),
    ("97", "Vaupés"),
    ("99", "Vichada"),
)

_countries = sa.table(
    "countries",
    sa.column("id", sa.Integer),
    sa.column("iso_code", sa.String),
    sa.column("name", sa.String),
)
_departments = sa.table(
    "departments",
    sa.column("country_id", sa.Integer),
    sa.column("dane_code", sa.String),
    sa.column("name", sa.String),
)


def upgrade() -> None:
    op.bulk_insert(
        _countries,
        [{"iso_code": iso_code, "name": name} for iso_code, name in _COUNTRIES],
    )

    # Read the id back rather than assume it: it comes from a sequence, and the
    # departments have to hang off whichever one Colombia was given.
    colombia_id = (
        op.get_bind()
        .execute(sa.select(_countries.c.id).where(_countries.c.iso_code == _COLOMBIA))
        .scalar_one()
    )

    op.bulk_insert(
        _departments,
        [
            {"country_id": colombia_id, "dane_code": dane_code, "name": name}
            for dane_code, name in _DEPARTMENTS
        ],
    )


def downgrade() -> None:
    # Cities first: they point at the departments. In practice the previous
    # revision drops all three tables, but a standalone downgrade has to work.
    op.execute(sa.text("DELETE FROM cities"))
    op.execute(sa.text("DELETE FROM departments"))
    op.execute(sa.text("DELETE FROM countries"))
