"""add location catalogs and third parties

Creates the country/department/city catalogs and the single `third_parties`
table that holds both natural persons and legal entities, plus the nullable link
from `users`: a login may belong to a third party, and a third party exists
without ever having one.

The catalogs are created empty here; the next revision fills them.

Revision ID: 7c980446df2a
Revises: c4d1ae763391
Create Date: 2026-07-26 04:43:25.663425

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "7c980446df2a"
down_revision: str | None = "c4d1ae763391"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "countries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("iso_code", sa.String(length=2), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_countries_iso_code"), "countries", ["iso_code"], unique=True
    )
    op.create_index(op.f("ix_countries_name"), "countries", ["name"], unique=False)
    op.create_table(
        "departments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("country_id", sa.Integer(), nullable=False),
        sa.Column("dane_code", sa.String(length=2), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["country_id"], ["countries.id"], onupdate="CASCADE", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "country_id", "dane_code", name="uq_departments_country_code"
        ),
    )
    op.create_index(
        op.f("ix_departments_country_id"), "departments", ["country_id"], unique=False
    )
    op.create_index(op.f("ix_departments_name"), "departments", ["name"], unique=False)
    op.create_table(
        "cities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("dane_code", sa.String(length=5), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cities_dane_code"), "cities", ["dane_code"], unique=True)
    op.create_index(
        op.f("ix_cities_department_id"), "cities", ["department_id"], unique=False
    )
    op.create_index(op.f("ix_cities_name"), "cities", ["name"], unique=False)
    op.create_table(
        "third_parties",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "person_type",
            sa.Enum(
                "NATURAL",
                "LEGAL",
                name="third_party_person_type",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "document_type",
            sa.Enum(
                "CITIZEN_ID",
                "FOREIGNER_ID",
                "NIT",
                "MINOR_ID",
                "PASSPORT",
                "BIRTH_CERTIFICATE",
                "NUIP",
                name="third_party_document_type",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("document_number", sa.String(length=20), nullable=False),
        sa.Column("check_digit", sa.Integer(), nullable=True),
        sa.Column("first_name", sa.String(length=50), nullable=True),
        sa.Column("middle_name", sa.String(length=50), nullable=True),
        sa.Column("first_surname", sa.String(length=50), nullable=True),
        sa.Column("second_surname", sa.String(length=50), nullable=True),
        sa.Column("issue_date", sa.Date(), nullable=True),
        sa.Column("issue_city_id", sa.Integer(), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("birth_country_id", sa.Integer(), nullable=True),
        sa.Column("birth_department_id", sa.Integer(), nullable=True),
        sa.Column("birth_city_id", sa.Integer(), nullable=True),
        sa.Column(
            "gender",
            sa.Enum(
                "MALE",
                "FEMALE",
                name="third_party_gender",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column(
            "marital_status",
            sa.Enum(
                "SINGLE",
                "MARRIED",
                "DOMESTIC_PARTNERSHIP",
                "FEMALE_HEAD_OF_HOUSEHOLD",
                "OTHER",
                name="third_party_marital_status",
                native_enum=False,
                length=30,
            ),
            nullable=True,
        ),
        sa.Column(
            "housing_type",
            sa.Enum(
                "OWNED",
                "RENTED",
                "FAMILY",
                "OTHER",
                name="third_party_housing_type",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column(
            "education_level",
            sa.Enum(
                "PRIMARY",
                "SECONDARY",
                "TECHNICAL",
                "UNIVERSITY",
                "POSTGRADUATE",
                name="third_party_education_level",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column("profession", sa.String(length=80), nullable=True),
        sa.Column("legal_name", sa.String(length=150), nullable=True),
        sa.Column(
            "company_type",
            sa.Enum(
                "CORPORATION",
                "LIMITED_LIABILITY",
                "SIMPLIFIED_JOINT_STOCK",
                "LIMITED_PARTNERSHIP_BY_SHARES",
                "DE_FACTO_PARTNERSHIP",
                "SOLE_PROPRIETORSHIP",
                "COOPERATIVE",
                "NONPROFIT",
                "FOUNDATION",
                "TRADE_ASSOCIATION",
                "CONSORTIUM",
                "TEMPORARY_JOINT_VENTURE",
                name="third_party_company_type",
                native_enum=False,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("company_nature", sa.String(length=120), nullable=True),
        sa.Column(
            "legal_rep_document_type",
            sa.Enum(
                "CITIZEN_ID",
                "FOREIGNER_ID",
                "NIT",
                "MINOR_ID",
                "PASSPORT",
                "BIRTH_CERTIFICATE",
                "NUIP",
                name="third_party_legal_rep_document_type",
                native_enum=False,
                length=30,
            ),
            nullable=True,
        ),
        sa.Column("legal_rep_document_number", sa.String(length=20), nullable=True),
        sa.Column("legal_rep_name", sa.String(length=150), nullable=True),
        sa.Column("trade_name", sa.String(length=150), nullable=True),
        sa.Column("address", sa.String(length=120), nullable=True),
        sa.Column("country_id", sa.Integer(), nullable=True),
        sa.Column("department_id", sa.Integer(), nullable=True),
        sa.Column("city_id", sa.Integer(), nullable=True),
        sa.Column("mobile_phone", sa.String(length=20), nullable=True),
        sa.Column("landline", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=120), nullable=True),
        sa.Column(
            "tax_regime",
            sa.Enum(
                "NOT_VAT_RESPONSIBLE",
                "VAT_RESPONSIBLE",
                "SIMPLIFIED",
                "SUBSIDIZED",
                name="third_party_tax_regime",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("foreign_operations", sa.Boolean(), nullable=False),
        sa.Column("public_resources", sa.Boolean(), nullable=False),
        sa.Column("public_recognition", sa.Boolean(), nullable=False),
        sa.Column("public_power", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["birth_city_id"], ["cities.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["birth_country_id"], ["countries.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["birth_department_id"], ["departments.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["city_id"], ["cities.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["country_id"], ["countries.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["issue_city_id"], ["cities.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_type", "document_number", name="uq_third_parties_document"
        ),
    )
    op.create_index(
        op.f("ix_third_parties_deleted_at"),
        "third_parties",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_third_parties_document_number"),
        "third_parties",
        ["document_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_third_parties_person_type"),
        "third_parties",
        ["person_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_third_parties_person_type"), table_name="third_parties")
    op.drop_index(op.f("ix_third_parties_document_number"), table_name="third_parties")
    op.drop_index(op.f("ix_third_parties_deleted_at"), table_name="third_parties")
    op.drop_table("third_parties")
    op.drop_index(op.f("ix_cities_name"), table_name="cities")
    op.drop_index(op.f("ix_cities_department_id"), table_name="cities")
    op.drop_index(op.f("ix_cities_dane_code"), table_name="cities")
    op.drop_table("cities")
    op.drop_index(op.f("ix_departments_name"), table_name="departments")
    op.drop_index(op.f("ix_departments_country_id"), table_name="departments")
    op.drop_table("departments")
    op.drop_index(op.f("ix_countries_name"), table_name="countries")
    op.drop_index(op.f("ix_countries_iso_code"), table_name="countries")
    op.drop_table("countries")
    # ### end Alembic commands ###
