"""add vouchers and third party flag on accounts

Adds the voucher header and its lines, and the flag on `accounts` that decides
whether an entry on that account must name a third party — which is what turns
"a third party where applicable" into a rule instead of a convention.

There is no company table: this deployment keeps one set of books, so the
issuing company lives in settings.

Revision ID: b90bd56725f4
Revises: d204a471ea58
Create Date: 2026-07-26 05:52:15.977498

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "b90bd56725f4"
down_revision: str | None = "d204a471ea58"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vouchers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("period_year", sa.Integer(), nullable=False),
        sa.Column("period_month", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "POSTED", name="voucher_status", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("posted_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("posted_by_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "period_month BETWEEN 1 AND 12", name="ck_vouchers_period_month"
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["posted_by_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("number", name="uq_vouchers_number"),
    )
    op.create_index(
        op.f("ix_vouchers_created_by_user_id"),
        "vouchers",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(op.f("ix_vouchers_date"), "vouchers", ["date"], unique=False)
    op.create_index(
        "ix_vouchers_period",
        "vouchers",
        ["period_year", "period_month"],
        unique=False,
    )
    op.create_index(op.f("ix_vouchers_status"), "vouchers", ["status"], unique=False)
    op.create_table(
        "voucher_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("voucher_id", sa.Integer(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("account_code", sa.String(length=20), nullable=False),
        sa.Column("third_party_id", sa.Integer(), nullable=True),
        sa.Column("debit", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("credit", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "(debit = 0) <> (credit = 0)", name="ck_voucher_lines_one_column"
        ),
        sa.CheckConstraint("debit >= 0 AND credit >= 0", name="ck_voucher_lines_signs"),
        sa.ForeignKeyConstraint(
            ["account_code"], ["accounts.code"], onupdate="CASCADE", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["third_party_id"], ["third_parties.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["voucher_id"], ["vouchers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("voucher_id", "line_number", name="uq_voucher_lines_order"),
    )
    op.create_index(
        op.f("ix_voucher_lines_account_code"),
        "voucher_lines",
        ["account_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_voucher_lines_third_party_id"),
        "voucher_lines",
        ["third_party_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_voucher_lines_voucher_id"),
        "voucher_lines",
        ["voucher_id"],
        unique=False,
    )
    op.add_column(
        "accounts",
        sa.Column(
            "requires_third_party",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.alter_column("accounts", "requires_third_party", server_default=None)

def downgrade() -> None:
    op.drop_column("accounts", "requires_third_party")
    op.drop_index(op.f("ix_voucher_lines_voucher_id"), table_name="voucher_lines")
    op.drop_index(op.f("ix_voucher_lines_third_party_id"), table_name="voucher_lines")
    op.drop_index(op.f("ix_voucher_lines_account_code"), table_name="voucher_lines")
    op.drop_table("voucher_lines")
    op.drop_index(op.f("ix_vouchers_status"), table_name="vouchers")
    op.drop_index("ix_vouchers_period", table_name="vouchers")
    op.drop_index(op.f("ix_vouchers_date"), table_name="vouchers")
    op.drop_index(op.f("ix_vouchers_created_by_user_id"), table_name="vouchers")
    op.drop_table("vouchers")
    # ### end Alembic commands ###
