"""add accounting periods

Only closed periods get a row: a month nobody has closed is open, so the books
work from the first day without anyone having to create months first. That is
why there is no seed here and no status default of `OPEN`.

Revision ID: d1c211d94b23
Revises: b90bd56725f4
Create Date: 2026-07-26 06:04:42.445045

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "d1c211d94b23"
down_revision: str | None = "b90bd56725f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounting_periods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN", "CLOSED", name="period_status", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("changed_at", sa.DateTime(), nullable=True),
        sa.Column("changed_by_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "month BETWEEN 1 AND 12", name="ck_accounting_periods_month"
        ),
        sa.ForeignKeyConstraint(
            ["changed_by_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("year", "month", name="uq_accounting_periods_month"),
    )
    op.create_index(
        op.f("ix_accounting_periods_status"),
        "accounting_periods",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accounting_periods_year"), "accounting_periods", ["year"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_accounting_periods_year"), table_name="accounting_periods")
    op.drop_index(op.f("ix_accounting_periods_status"), table_name="accounting_periods")
    op.drop_table("accounting_periods")
    # ### end Alembic commands ###
