"""add voucher reversal link

A reversal is a voucher like any other; what marks it is pointing at the one it
undoes. The link is unique so a voucher cannot be reversed twice, which would
double the correction instead of cancelling it.

Revision ID: e0b85c326d15
Revises: d1c211d94b23
Create Date: 2026-07-26 06:14:01.898849

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "e0b85c326d15"
down_revision: str | None = "d1c211d94b23"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vouchers", sa.Column("reverses_voucher_id", sa.Integer(), nullable=True)
    )
    op.create_unique_constraint(
        "uq_vouchers_reverses_voucher_id", "vouchers", ["reverses_voucher_id"]
    )
    # Named explicitly: autogenerate leaves it None, which lets Postgres invent
    # a name on the way up and leaves `downgrade` with nothing to drop.
    op.create_foreign_key(
        "fk_vouchers_reverses_voucher_id",
        "vouchers",
        "vouchers",
        ["reverses_voucher_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_vouchers_reverses_voucher_id", "vouchers", type_="foreignkey")
    op.drop_constraint("uq_vouchers_reverses_voucher_id", "vouchers", type_="unique")
    op.drop_column("vouchers", "reverses_voucher_id")
    # ### end Alembic commands ###
